// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfqX0MTxASCdKAK8MEVBgIKprGTMRrEY',
    appId: '1:106588962525:web:db0f853223fb106024e534',
    messagingSenderId: '106588962525',
    projectId: 'control-gastos-6990c',
    authDomain: 'control-gastos-6990c.firebaseapp.com',
    storageBucket: 'control-gastos-6990c.firebasestorage.app',
    measurementId: 'G-4T617H3CJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA94mkY2lGn_YNjbDSMsZit9dCc2SryOmY',
    appId: '1:106588962525:android:44a3f9160c06479024e534',
    messagingSenderId: '106588962525',
    projectId: 'control-gastos-6990c',
    storageBucket: 'control-gastos-6990c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2WA_H7SjqUBlo1nY6m8pxD0KUZw0kBY',
    appId: '1:106588962525:ios:a4e721551203a2d224e534',
    messagingSenderId: '106588962525',
    projectId: 'control-gastos-6990c',
    storageBucket: 'control-gastos-6990c.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionesMoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh2WA_H7SjqUBlo1nY6m8pxD0KUZw0kBY',
    appId: '1:106588962525:ios:a4e721551203a2d224e534',
    messagingSenderId: '106588962525',
    projectId: 'control-gastos-6990c',
    storageBucket: 'control-gastos-6990c.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionesMoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHfqX0MTxASCdKAK8MEVBgIKprGTMRrEY',
    appId: '1:106588962525:web:557cb260eefc29f624e534',
    messagingSenderId: '106588962525',
    projectId: 'control-gastos-6990c',
    authDomain: 'control-gastos-6990c.firebaseapp.com',
    storageBucket: 'control-gastos-6990c.firebasestorage.app',
    measurementId: 'G-GMMXEYTXSL',
  );
}
